name: This workflow will get the file from runner and upload to github
on:
 push:
  branches: 
   - master
jobs:
  uploadfile:
    runs-on: ubuntu-latest
    steps:
     - name: create a directory
       run: mkdir myfiles
     - name: create a file in directory
       run: echo "heallo" > /myfiles/file1
     - name: upload the file to github
       uses: actions/upload-artifact@v4
       with:
        name: my-file
        path: /myfiles/file1
